<?php

return [
    'alerta' => [
        'subject' => 'Lotus — suspicious access alert',
        'greeting' => 'Security alert',
        'familia' => [
            'login_falho_repetido' => 'Repeated failed sign-in attempts from the same origin key.',
            'sessao_de_conta_desativada' => 'Use of a session belonging to a deactivated account.',
            'sequencia_de_403' => 'Sequence of authorization denials.',
        ],
        'ocorrencias' => 'Recorded occurrences: :ocorrencias',
        'ip' => 'IP address: :ip',
        'usuario' => 'User involved: :usuario',
        'sem_usuario' => 'No authenticated user identified.',
        'rodape' => 'This notice is generated by the system itself. Check the security log for details.',
    ],
];
